// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CustomColumnHeader: typeof import('./components/CustomColumnHeader.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FilterInput: typeof import('./components/FilterInput.vue')['default']
    IPhCloudMoonBold: typeof import('~icons/ph/cloud-moon-bold')['default']
    IPhSignInBold: typeof import('~icons/ph/sign-in-bold')['default']
    IPhSunHorizonBold: typeof import('~icons/ph/sun-horizon-bold')['default']
    IPhTextIndent: typeof import('~icons/ph/text-indent')['default']
    IPhTextOutdent: typeof import('~icons/ph/text-outdent')['default']
    SelectCampo: typeof import('./components/campos/SelectCampo.vue')['default']
    SelectCatalogo: typeof import('./components/catalogos/SelectCatalogo.vue')['default']
    SelectRol: typeof import('./components/SelectRol.vue')['default']
    SelectTipoCarta: typeof import('./components/tipoCartas/SelectTipoCarta.vue')['default']
    SelectType: typeof import('./components/SelectType.vue')['default']
    SelectUsuario: typeof import('./components/usuarios/SelectUsuario.vue')['default']
    ShowUser: typeof import('./components/ShowUser.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
  }
}

export { }
