// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CustomColumnHeader: typeof import('./components/CustomColumnHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FilterInput: typeof import('./components/FilterInput.vue')['default']
    IPhCloudMoonBold: typeof import('~icons/ph/cloud-moon-bold')['default']
    IPhSunHorizonBold: typeof import('~icons/ph/sun-horizon-bold')['default']
    SelectCampo: typeof import('./components/campos/SelectCampo.vue')['default']
    SelectCatalogo: typeof import('./components/catalogos/SelectCatalogo.vue')['default']
    SelectRol: typeof import('./components/SelectRol.vue')['default']
    SelectTipoCarta: typeof import('./components/tipoDocumentos/SelectTipoCarta.vue')['default']
    SelectType: typeof import('./components/SelectType.vue')['default']
    SelectUsuario: typeof import('./components/usuarios/SelectUsuario.vue')['default']
    ShowUser: typeof import('./components/ShowUser.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
  }
}

export { }
